version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-container
    environment:
      - 'ACCEPT_EULA=Y'
      - 'MSSQL_SA_PASSWORD=Str0ngPassword!123'  # Ensure the password meets complexity requirements
    ports:
      - "1433:1433"
